apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: python:3
          workingDir: /app
          command: [ 'bash', 'rest.sh' ]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: app-volume
              mountPath: /app
          resources:
            limits:
              cpu: "500m"
              memory: "200Mi"
      volumes:
        - name: app-volume
          configMap:
            name: rest-api

---
apiVersion: v1
kind: Service
metadata:
  name: rest-api
spec:
  selector:
    app: rest-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rest-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: rest-api
          servicePort: 8000

